### ISSUE TITLE
Allow pip installation of packages into base

### ISSUE THREAD

**Issue by skwde** [mamba-org/devcontainer-features#28]
Consider following environment file:

```yml
---
name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip>=10.0
  - pip:
      - pymarkdownlnt
```

To my understanding installing this base environment is not possible by just using the feature.

A `postCreateCommand` has to be used.

Related: https://github.com/mamba-org/devcontainer-features/issues/14
